### ISSUE TITLE
Iodine is undefined

### ISSUE THREAD

**Issue by antonioreyna** [mattkingshott/iodine#14]
Hello, I am including the Iodine library from cdn to my project, but when i try to use it on my script file i get 

```
Alpine Error: "ReferenceError: Can't find variable: Iodine"
```

I did a console.log to window object and i can see Iodine there.

**Comment by mattkingshott** [comment]
Hi there. 

It's difficult to suggest much based on what you've provided... but if I had to guess, I reckon either Alpine isn't referencing Iodine from the `window`, or Iodine hasn't finished loading before Alpine is accessing it.

The fact you can see Iodine in the `window` using `console.log` would suggest that this isn't an Iodine issue as such.

Can you post your code?
