### ISSUE TITLE
Update a single error only

### ISSUE THREAD

**Issue by PericlesTheo** [mattkingshott/iodine#18]
👋  would it make sense to have a similar function to

```js
Iodine.setErrorMessages({ same: `Field must be '[PARAM]'` }); 
```

where instead of replacing the whole set, it just replaces one?

probably something simple as
```js
 /**
   * Replace or add a single error message.
   *
   **/
function setErrorMessage(key, message) {
  this.messages[key] = message
}

 setErrorMessage("email",  "Are you sure this is a valid email?")
```

Usecase: I just want to update one of them https://github.com/mattkingshott/iodine/blob/master/src/iodine.js#L52 but if I replace it, I have to add the rest of them.

I think the only way to achieve this now which is still legit way is `Iodine.messages["email"] = "Are you sure this is a valid email?"` but maybe you shouldn't be able to do it like in general 😄 

Let me know if you think this is useful and I can fire up a PR. Codewise happy to use immutability/destruction if you prefer or browser support permits

Cheers

**Comment by mattkingshott** [comment]
This looks like a good idea. Feel free to PR the singular `setErrorMessage` using the approach that feels best. 👍🏻
