### ISSUE TITLE
Minimum and maximum rules validating numbers as strings

### ISSUE THREAD

**Issue by andrewpitts15** [mattkingshott/iodine#20]
The minimum and maximum validation rules incorrectly validate numerical values based on their length instead of their value when programmatically passing a element's value to the validation function. 

```
Iodine.is(element.value, ['minimum:10'])
````

The default validation messages for these rules are also inappropriate or confusing when validating numbers
```
      maximum: `Value must not be greater than '[PARAM]' in size or character length`,
      minimum: `Value must not be less than '[PARAM]' in size or character length`,
```

I propose deprecating the current function to prevent breaking changes, and then creating 'min' and 'max' rules for numbers and 'minlength' and 'maxlength' rules for validating string length. This would be more in keeping with the naming conventions used on html inputs.

**Comment by mattkingshott** [comment]
Thanks for getting in touch. I'd be happy to accept a PR for this.
