### ISSUE TITLE
Error after adding CDN

### ISSUE THREAD

**Issue by Pab89** [mattkingshott/iodine#26]
Hi there

Thanks for a great plugin. :) Been playing around with it for a couple of days, and it is just great.

One minor problem though. As soon as i add the CDN to mig html "<script src="https://cdn.jsdelivr.net/gh/mattkingshott/iodine/dist/iodine.min.js" defer></script>"

I get the following error in my console (see screenshot). This also happens if I remove all code related to Iodine.

![image](https://user-images.githubusercontent.com/2759517/131989017-cf35f6d2-ad25-47e7-b319-1f74f07de583.png)

**Comment by mattkingshott** [comment]
Have you tried using one of the other builds e.g. modern, umd, mjs? They’re in the dist folder

**Comment by Pab89** [comment]
Thanks for the very fast response. I get the same error for modern.
![image](https://user-images.githubusercontent.com/2759517/131995332-0f321361-1032-41cf-9f59-f6a42210cf82.png)

But umd works! :) Can i ask what the difference on these versions are ?

**Comment by mattkingshott** [comment]
They’re just different builds that have different levels of browser feature expectation. UMD basically assumes nothing :)
