### ISSUE TITLE
Async validate rules

### ISSUE THREAD

**Issue by Tim-Wils** [mattkingshott/iodine#27]
Hey Matt! First of all, thanks for the great simple plugin!

I use this library in a few projects now, but now we walk into a thing where email had to be validated against the server for being unique.
We quickfixed this for now by overwriting the is() function, but maybe you know a better solution?

Our solution right now:
```
Iodine.is = async function(value, rules = []) {
	if (!rules.length) return true;
  
	if (rules[0] === "optional" && this.isOptional(value)) return true;
  
	for (let index in rules) {
	  if (rules[index] === "optional") continue;
  
	  const chunks = rules[index].split(":");
	  const ruleName = chunks.shift();
	  let rule = ruleName[0].toUpperCase() + ruleName.slice(1);
  
	  let result = await this[`is${rule}`].apply(this, [value, chunks.join(":")]);
  
	  if (!result) return await rules[index];
	}
  
	return true;
};
```

Or is this good enough to be added?

Tim

**Comment by Tim-Wils** [comment]
Hey Matt, thanks for replying!

We are already applying a custom uniqueEmail rule which resolves ajax call in a Promise. With the current is() function the rule always returns true. That’s why we bypassed the synchronous return and made it work async.

**Comment by mattkingshott** [comment]
Oh I see, yes, in theory that should be fine.

Feel free to submit a PR. Assuming all the tests pass, I'll merge it in :)
