### ISSUE TITLE
Uncaught ReferenceError: exports is not defined at iodine.min.js:1

### ISSUE THREAD

**Issue by tokenmasterpro** [mattkingshott/iodine#33]
Hello Iodine Team Member, 
   I was trying to integrate Iodine in a project using CDN link and got into the error Uncaught ReferenceError: exports is not defined at iodine.min.js:1

**Comment by mattkingshott** [comment]
Hi there. Thanks for reporting this. I’ll take a look at it this weekend.

**Comment by mattkingshott** [comment]
Apologies, you need to use the UMD build for CDN. I've updated the readme to fix this.

```html
<script src="https://cdn.jsdelivr.net/gh/mattkingshott/iodine/dist/iodine.min.umd.js" defer></script>
```
