### ISSUE TITLE
Optionally return an array of all validation rules that were unmet

### ISSUE THREAD

**Issue by aschmelyun** [mattkingshott/iodine#34]
First off, really enjoying Iodine and using it as a drop-in library for validation. The one small hiccup that I have with it is when using multiple rules to validate a value.

For instance, if I use

```js
Iodine.is('test', ['required', 'email', 'min:5']);
```

I'm only getting back `email` since it was the first rule that was validated. If a user then fixes that issue, but didn't realize that there's also a minimum character amount, it'll error again when re-validating on `min:5`.

Would you accept a PR that included an optional boolean parameter for the `.is()` method that will check all rules and return an array of those that didn't match?

```js
Iodine.js('test', ['required', 'email', 'min:5'], true);

// returns ['email', 'min:5'];
```

**Comment by mattkingshott** [comment]
Hi,

I’m open to the idea, but I’m not sure if I like the approach of a Boolean parameter.

I wonder if it should be available as a separate method? Maybe something like isValidAll? Not sure about the name.

**Comment by aschmelyun** [comment]
Yeah that's a tough one, because something like `isValidAll` or even `isAll` implies that I want all of the validation rules to be met, which is basically the default behavior. It's more about a change of _return_ versus validation.

Maybe `isValidArray`? or `isValidList`?

**Comment by mattkingshott** [comment]
Maybe a submit a PR and I’ll see if I can think of a good name. To be honest, it may be time for some refactoring and new major version. Things like is and isValid are bit ambiguous.

**Comment by mattkingshott** [comment]
But I’d like to include the feature in a new version.

**Comment by aschmelyun** [comment]
Sounds good, will do! Also if you need any help with that refactor feel free to reach out!

**Comment by mattkingshott** [comment]
Thanks. Will do 👍🏻
