### ISSUE TITLE
isInteger to support strings that are integers

### ISSUE THREAD

**Issue by jameskennard** [mattkingshott/iodine#35]
It would be nice if the integer rule allowed for strings that contained an integer. Or for backwards compatibility and more control if there was a looser variation.

```
let item_1 = 7;
let item_2 = 'string';
let item_3 = ' 8 ';

Iodine.is(item_1, ['required', 'integer']); // true
Iodine.is(item_2, ['required', 'integer']); // string - 'integer'
Iodine.is(item_3, ['required', 'integer']); // true
```

**Comment by mattkingshott** [comment]
Thanks for asking. There are no plans to add this.

If you want a looser checking option, then you can add a custom rule. 👍🏻
