### ISSUE TITLE
Dunamic Input name with index vallidation 

### ISSUE THREAD

**Issue by thedigifrog** [mattkingshott/iodine#36]
Thanks for awesome solution for validation.

I have a dynamic input call expertise. and its cloned multiple time  and the input name something like this:

`
<input name="user[0][expertise]"/>
<input name="user[1][expertise]"/>
<input name="user[2][expertise]"/>
`

How to validate above mentioned inputs using Iodine?

Thanks in advance

**Comment by mattkingshott** [comment]
Hello.

You'd need to use javascript to create a method that would dynamically construct the Iodine validation process based on what inputs exist.
