### ISSUE TITLE
email/numeric and maxLenght doesn't work

### ISSUE THREAD

**Issue by scenoxshift** [mattkingshott/iodine#37]
`['required', 'email', 'maxLength:199']`

`['required', 'maxLength:199', 'numeric']`

If i put email/numeric and maxLength in the rules its not working...

Can we get a fast fix for this?

**Comment by mattkingshott** [comment]
Use `max` for numbers, not `maxLength`. 

Max length is for the number of characters.

**Comment by scenoxshift** [comment]
What about the first one for email?
