### ISSUE TITLE
this in addRule?

### ISSUE THREAD

**Issue by QJan84** [mattkingshott/iodine#38]
**HTML:**
`data-rules='["required", "ExampleRuleName"]'`
**JS:**
`Iodine.addRule("ExampleRuleName",(value, param) => { console.log("Current Input: ", this); ...`

1.) Is there something like `this` in addRule?
2.) I have rules that are linked or dependent on other elements. Can I therefore specify a "target element" via the HTML, which is used for verification?

Maybe in that way?
**HTML:**
`data-rules='["required", "ExampleRuleName({ target: '#idToTargetElement', group: '[data-validate-group]'  }) "]'`

**Comment by mattkingshott** [comment]
Iodine isn’t designed for complex scenarios like that. It’s supposed to be for minimal and lite validation.
