### ISSUE TITLE
Showing valid email for invalid email address

### ISSUE THREAD

**Issue by sandeeprvarma** [mattkingshott/iodine#40]
I was validating random keywords in the below format and the validation does not show any error. 

Email: lsdflksdajfkl;@kdsjf;ksadjf;s.dsfk

We can try the below regex for validating emails and it seems to be more accurate:

^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$

**Comment by mattkingshott** [comment]
I will make a note to review this but in the mean time, you can use the `isRegexMatch` rule with the above regex.
