### ISSUE TITLE
Date Format Validation

### ISSUE THREAD

**Issue by davidgualvez** [mattkingshott/iodine#42]
Hi!,

How to validate Date with a certain accepted format like: mm/dd/yyyy

**Comment by mattkingshott** [comment]
Hi. You should use isRegexMatch and provide a regular expression for the date format.

**Comment by stepanjakl** [comment]
Hi, I would like to contribute to this issue with a solution.

```
const regex = /^(?:(?:1[6-9]|[2-9]\d)?\d{2})(?:(?:(\/|-|\.)(?:0?[13578]|1[02])\1(?:31))|(?:(\/|-|\.)(?:0?[13-9]|1[0-2])\2(?:29|30)))$|^(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00)))(\/|-|\.)0?2\3(?:29)$|^(?:(?:1[6-9]|[2-9]\d)?\d{2})(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:0?[1-9]|1\d|2[0-8])$/
Iodine.assertRegexMatch(element.value, regex)
```
...where the `element` variable is the input `type='date'` element.

It may work inside the `data-rules` attribute e.g. `data-rules='["required", "regexMatch:/^(?:(?:1[6-9]|[2..."]'` in the HTML template, but I haven't tested it. It probably wouldn't make sense to have such a long regex expression there anyway.

Regex code inspired by: https://stackoverflow.com/a/26972181/11035513
