### ISSUE TITLE
API change

### ISSUE THREAD

**Issue by nainardev** [mattkingshott/iodine#5]
Instead of exporting a Class, we could export an object containing all these helper functions

This helps us destructure functions we want resulting in treee shaking and better compression

this also helps  us to write
```js
import { isArray, isSame } from '@kingshott/iodine'
```

**Comment by mattkingshott** [comment]
Hmm...

I have a couple of questions in relation to this:

1. Would this introduce a breaking change to the current approach? If we're no longer exporting a class, would it no longer be possible to do something like `Iodine.isEmail()`, or are we just reassigning `window.Iodine` to something else? An example would be very helpful as I'm not familiar with tree shaking etc.

2. If the motivation is primarily compression, I'm not sure it's worth it. The entire library is only 1.5 KB when gzipped and is even less with Brotli. Will shaving off a few hundred bytes make much difference?

Thanks for your feedback!

**Comment by nainardev** [comment]
like how lodash does

**Comment by mattkingshott** [comment]
I'm still not really sold on the idea for this. I'd like to see an example highlighting how this would be beneficial before taking it any further. Simply referencing another library is also not ideal, as I'm not sure what I'm supposed to be looking for. Thanks!

**Comment by nainardev** [comment]
Ok just tell me that if I can,
```js
import { isEmail } from '@kingshott/iodine'
```

**Comment by mattkingshott** [comment]
I think I'm going to close this for the reasons mentioned earlier. 

If you really want this implemented, I'm going to need an example of how this would be done, not simply the end result of a destructurable import statement. It would also have to be done in a way that wouldn't introduce a major breaking change.
