### ISSUE TITLE
Link to version 7 in readme is broken

### ISSUE THREAD

**Issue by hankhank10** [mattkingshott/iodine#50]
Hi Matt,

I just spent a good hour trying to work out why my code wasn't working properly before working out that it was a breaking change at the iodine side from the latest version. That'll teach me not to explicitly include version numbers in my CDN links...

In any case, the link to version 7 in your readme delivers a 404 so would be worth updating that:

<img width="859" alt="image" src="https://user-images.githubusercontent.com/25515609/183941269-de56d042-d741-46fd-8dd4-62f34e2132e7.png">

**Comment by mattkingshott** [comment]
Thanks. Fixed it :)
