### ISSUE TITLE
undefined is not an object in custom rule when value containing special characters

### ISSUE THREAD

**Issue by madsem** [mattkingshott/iodine#52]
Hey there,

I'm running into an issue when trying to validate an input using custom rules.
I get an  error with a value like this: `&987`

With these rules:
```js
/**
     * Custom Validation Rules
     */
    validator.rule("onlyLettersNumbers", (value) => {
      console.log(value);
      return /^[a-zA-Z0-9]+$/.test(value);
    });
    validator.rule("onlyLetters", (value) => {
      console.log(value);
      return /^[a-zA-Z]+$/.test(value);
    });
```

Without the ampersand in the value, it works like a charm.

Specific error message in console:
`TypeError: undefined is not an object (evaluating 's.replace')`

**Comment by madsem** [comment]
I think I know what is happening here...

When I further customized Iodine and added custom error messages, the error disappeared ... :)

```js
/**
     * Custom Validation Rules & Error Messages
     */
    validator.setErrorMessages({
      required: "This field cannot be empty.",
      onlyLettersNumbers: "This field cannot contain special characters.",
      onlyLetters: "This field can only contain letters."
    });

    validator.rule("onlyLettersNumbers", (value) =>
      /^[a-zA-Z0-9\s]+$/.test(value)
    );

    validator.rule("onlyLetters", (value) => /^[a-zA-Z\s]+$/.test(value));
```

Now, same code throws no error. So the issue is where Iodine replaces the `[FIELD]` and `[PARAM]`

**Comment by mattkingshott** [comment]
So are you saying that after you added a custom error message, it worked fine?

That’s what you should do with all new rules.

**Comment by madsem** [comment]
I didn't realize that was required sorry.

But just now I also had the issue with the `email` rule, when I set a custom email message the `s.replace` error disappeared.


This is how I call the validator:
```js
async fieldValidation(field) {
    const validator = new Iodine();
    const validationRules = JSON.parse(field.getAttribute("data-validation"));
    let value = field.value.trim();

    /**
     * Custom Validation Rules & Error Messages
     */
    validator.setErrorMessages({
      required: "This field cannot be empty.",
      email: "Must be a valid email address.",
      onlyLettersNumbers: "This field cannot contain special characters.",
      onlyLetters: "This field can only contain letters.",
    });

    validator.rule("onlyLettersNumbers", (value) =>
      /^[a-zA-Z0-9\s]+$/.test(value)
    );

    validator.rule("onlyLetters", (value) => /^[a-zA-Z\s]+$/.test(value));

    /**
     * Validate Field Value
     */
    const validationResult = validator.assert(value, validationRules);
```

**Comment by mattkingshott** [comment]
No worries. I’m not at my desk today so I’ll have to take a look next week. 👍🏻

**Comment by madsem** [comment]
Thanks!

Just to verify, the `[PARAM]` token works just fine, but the messages with `[FIELD]` throw errors for single item assertions.

**Comment by mattkingshott** [comment]
I haven’t forgotten about this. I’m just dealing with flu at the moment.

**Comment by mattkingshott** [comment]
So, I've spent some time with this today and I'm having trouble reproducing it. Can you modify the example test (adapted from your code) below to generate the error you are experiencing:

```js
test('example of the issue', () =>
{
    let rules = [
        'required', 
        'email'
    ];

    let messages = {
        required: 'This field cannot be empty.',
        email: 'Must be a valid email address.',
    }

    let result = {
        valid : true,
        rule  : '',
        error : '',
    };

    window.Iodine.setErrorMessages(messages);

    expect(window.Iodine.assert('test@gmail.com', rules)).toStrictEqual(result);
});
```

**Comment by madsem** [comment]
Hey @mattkingshott 

thanks a lot for looking into this :) Appreciate you!

The test case above, has custom messages.

Try running it with the default messages Iodine provides, for a single validation.
It should then error out due to the `[FIELD]` replacement token (As single validations don't take a field name)

IF this is how Iodine is supposed to be used (Ie: custom error messages when using the single validation method), it was not clear to me.

**Comment by mattkingshott** [comment]
Apologies. This went into my junk. Will check it out tomorrow.

**Comment by mattkingshott** [comment]
Sorry, but I still can't reproduce this. Please provide a full, failing example.
