### ISSUE TITLE
Form validation ideas for checkbox/radio-groups ?

### ISSUE THREAD

**Issue by Tim-Wils** [mattkingshott/iodine#7]
Not a bug, but a question related to validate checkboxes and radiobuttons :)
I want to validate a form with the rules in alpinejs and inputs that are validated with onInput and onSubmit. 
I got that working for flat inputs/textareas ( as you described here: https://dev.to/mattkingshott/validating-a-form-with-iodinejs-1jon ), but I need some ideas to validate checkboxes like so: min-checked:1, max-checked:1, required

How would you validate 'required', 'minchecked', 'maxchecked' for multiple checkboxes (name="check[]") and multiple radiobuttons (name="radioitem") ?

**Comment by mattkingshott** [comment]
I'm not entirely clear on whether you're asking about the rules to use or how you would actually get the values you want to validate, so I'll try to answer both...

1. For rules, I would get the value of the checkbox and then make some attempt to cast it to a boolean, then validate that with `isTruthy` or `isFalsy`. You can check the element's type using something like this:

```javascript
el.type === 'checkbox'
```

You might want to create a helper function that you pass all form elements to, this helper would then determine the form field type and return its corresponding value. Then you would just validate as per the article you linked.

2. For groups of elements, you'd need to write code that would inspect the element and determine if it was part of a group. Then you'd validate each item in the group. Combining this logic with the helper mention in step 1 might be a good idea.

Hope that helps.
