### ISSUE TITLE
Regex toLoweCase

### ISSUE THREAD

**Issue by kamundson2557** [mattkingshott/iodine#8]
Hello,
I like your library, just what you need for small projects👍 , but you need to fix this part, because some of regex tests not working with uppercase chars )
For example this will _Iodine.isRegexMatch("P54655465",/^P\d{3,}$/)_ always return false.

```
  isRegexMatch(value, expression) {
    return new RegExp(expression).test(String(value).toLowerCase());
  }

```
To something like 

```
  isRegexMatch(value, expression) {
    return new RegExp(expression).test(String(value));
  }
```

**Comment by mattkingshott** [comment]
Thanks for reporting this.

Fixed in v3.1.0
